#ifndef PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_CONSTRAINTS_H
#define PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_CONSTRAINTS_H


class Constraints {

};


#endif //PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_CONSTRAINTS_H
