#ifndef PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_EDGECRITERION_H
#define PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_EDGECRITERION_H


#include "PersistencyCriterion.h"

class EdgeCriterion: public PersistencyCriterion{

};


#endif //PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_EDGECRITERION_H
