#ifndef PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_EDGECRITERIONJOIN_H
#define PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_EDGECRITERIONJOIN_H


#include "EdgeCriterion.h"

class EdgeCriterionJoin: public EdgeCriterion {

};


#endif //PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_EDGECRITERIONJOIN_H
