#ifndef PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_EDGECRITERION_H
#define PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_EDGECRITERION_H


class EdgeCriterion {

};


#endif //PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_EDGECRITERION_H
