#ifndef PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_TRIANGLECRITERION_H
#define PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_TRIANGLECRITERION_H


#include "PersistencyCriterion.h"

class TriangleCriterion: public PersistencyCriterion {

};


#endif //PARTIALLY_OPTIMAL_SUBSPACE_CLUSTERING_TRIANGLECRITERION_H
